#!/bin/bash
# Open Nexuiz Map
# by Tyler "-z-" Mulligan
#
# This is a nautilus script.  When placed in ~/.gnome2/nautilus-scripts
# you will have the ability to right click >> open your nexuiz maps
#
# Both bsp and pk3 are supported.
#

# Set variables
nexuizdir="$HOME/Games/Nexuiz"
nexuizbin="nexuiz-linux-x86_64-glx"

if [[ "$(echo $1|awk -F . '{print $NF}')" == "pk3" ]]; then
	# Find the name of the bsp
	mapname=$(unzip -l $1 | grep .bsp | awk '{ print $4 }' | sed 's/maps\/\([A-Za-z_0-9.-]*\)\.bsp/\1/' | grep -vi .bsp)
fi

if [[ "$(echo $1|awk -F . '{print $NF}')" == "bsp" ]]; then
	mapname=$(basename $1 .bsp)
fi

# Run it
$nexuizdir/$nexuizbin -basedir $nexuizdir +map $mapname
